(function(root,factory){const api=factory();if(typeof module!=="undefined"&&module.exports)module.exports=api;root.VoiceLab=api})(typeof window!=="undefined"?window:globalThis,function(){
"use strict";
const QUESTIONS=[
 {question:"What is the largest ocean on Earth?",canonical:"Pacific Ocean",approved:["Pacific Ocean","Pacific","The Pacific"],early:["pacific"]},
 {question:"Who is credited with inventing the telephone?",canonical:"Alexander Graham Bell",approved:["Alexander Graham Bell","Graham Bell","Bell"],early:["graham bell","bell"]},
 {question:"What trophy is awarded to the NHL champion?",canonical:"Stanley Cup",approved:["Stanley Cup","The Stanley Cup","Stanley"],early:["stanley cup","stanley"]},
 {question:"What device helps a wheelchair enter a vehicle?",canonical:"Ramp or lift",approved:["Ramp","Wheelchair ramp","Lift","Wheelchair lift"],early:["ramp","lift","wheelchair ramp","wheelchair lift"],safeTranscriptions:{lyft:"Lift"}},
 {question:"What process did Darwin describe as a major mechanism of evolution?",canonical:"Natural selection",approved:["Natural selection","Evolution by natural selection","The theory of evolution by natural selection"],early:["natural selection"]}
];
const FILLERS=new Set(["a","an","the","answer","is","it","would","be","i","think","its"]);
const normalize=value=>String(value||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/&/g," and ").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
const meaningful=value=>normalize(value).split(" ").filter(word=>word&&!FILLERS.has(word)).join(" ");
function editDistance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let previous=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,previous+(a[i-1]===b[j-1]?0:1));previous=old}}return row[b.length]}
function evaluate(transcript,question,{isFinal=false,confidence=null,stableCount=1}={}){
 const heard=meaningful(transcript),forms=question.approved.map(meaningful),early=question.early.map(meaningful);
 if(!heard)return {accepted:false,score:0,reason:"No usable speech yet.",method:"empty"};
 const approvedIndex=forms.indexOf(heard);
 if(approvedIndex>=0)return {accepted:true,score:1,matchedAnswer:question.approved[approvedIndex],reason:`Exact approved answer: “${question.approved[approvedIndex]}”.`,method:"approved-exact"};
 const safeTarget=question.safeTranscriptions?.[heard],safeIndex=safeTarget==null?-1:forms.indexOf(meaningful(safeTarget));
 if(safeIndex>=0)return {accepted:true,score:.99,matchedAnswer:question.approved[safeIndex],reason:`Strong transcription-safe match to “${question.approved[safeIndex]}”.`,method:"controlled-transcription"};
 const contained=forms.find(form=>heard.includes(form)&&form.length>=4);
 if(contained){const index=forms.indexOf(contained);return {accepted:true,score:.98,matchedAnswer:question.approved[index],reason:`Approved answer clearly appeared: “${question.approved[index]}”.`,method:"approved-contained"}}
 const core=early.find(form=>heard===form||heard.includes(form));
 if(core){const index=forms.indexOf(core),matched=index>=0?question.approved[index]:core;return {accepted:true,score:.96,matchedAnswer:matched,reason:`Required core concept clearly appeared: “${matched}”.`,method:"core-concept"}}
 const candidates=[...new Set([...forms,...early])].filter(form=>form.length>=5),best=candidates.map(form=>({form,distance:editDistance(heard,form)})).sort((a,b)=>a.distance-b.distance)[0];
 const limit=best?Math.max(1,Math.floor(best.form.length*.16)):0,strong=best&&best.distance<=limit;
 if(strong&&(isFinal||stableCount>=2||Number(confidence)>=.82)){const index=forms.indexOf(best.form),matched=index>=0?question.approved[index]:best.form;return {accepted:true,score:Math.max(.86,1-best.distance/best.form.length),matchedAnswer:matched,reason:`Strong transcription-safe match to “${matched}”.`,method:"strong-similarity"}}
 if(strong)return {accepted:false,score:Math.max(.7,1-best.distance/best.form.length),matchedAnswer:best.form,reason:`Close match to “${best.form}”, but waiting for more evidence.`,method:"uncertain-similarity"};
 return {accepted:false,score:0,reason:"No approved answer or required core concept was clear.",method:"no-safe-match"};
}
function createAttempt(onAccept){let accepted=false,lastInterim="",stableCount=0;return {process(transcript,options={}){const normalized=meaningful(transcript);if(!options.isFinal){stableCount=normalized&&normalized===lastInterim?stableCount+1:1;lastInterim=normalized}const result=evaluate(transcript,options.question,{...options,stableCount});if(result.accepted&&!accepted){accepted=true;onAccept?.(result);return {...result,newAcceptance:true}}return {...result,newAcceptance:false,alreadyAccepted:accepted}},isAccepted:()=>accepted}}
function createAttemptClock(now=()=>performance.now()){
 let sequence=0,state;
 const reset=()=>state={attemptId:++sequence,attemptResetAt:now(),firstSpeechActivityAt:null,speechStartSource:null,firstTranscriptAt:null,acceptedAt:null,finalTranscriptAt:null};
 const current=()=>({...state}),valid=at=>Number.isFinite(at)&&at>=state.attemptResetAt;
 const recordSpeechActivity=(source,at=now())=>{if(!valid(at)||state.firstSpeechActivityAt!=null)return false;state.firstSpeechActivityAt=at;state.speechStartSource=source;return true};
 const recordTranscript=(isFinal=false,at=now())=>{if(!valid(at))return false;if(state.firstTranscriptAt==null)state.firstTranscriptAt=at;if(isFinal&&state.finalTranscriptAt==null)state.finalTranscriptAt=at;return true};
 const recordAccepted=(at=now())=>{if(!valid(at)||state.acceptedAt!=null)return false;state.acceptedAt=at;return true};
 const metrics=()=>({speechToFirstMs:state.firstSpeechActivityAt==null||state.firstTranscriptAt==null?null:state.firstTranscriptAt-state.firstSpeechActivityAt,speechToCorrectMs:state.firstSpeechActivityAt==null||state.acceptedAt==null?null:state.acceptedAt-state.firstSpeechActivityAt,firstToCorrectMs:state.firstTranscriptAt==null||state.acceptedAt==null?null:state.acceptedAt-state.firstTranscriptAt});
 reset();return {reset,current,recordSpeechActivity,recordTranscript,recordAccepted,metrics};
}
const formatLatency=value=>value==null?"Unavailable":`${value.toFixed(1)} ms`;
function friendlyRecognitionError(error){const code=String(error||"");if(code==="insecure-context")return "A secure HTTPS connection is required.";if(code==="unsupported")return "Speech recognition is not supported on this browser.";if(code==="not-allowed"||code==="service-not-allowed")return "Microphone or speech recognition permission was denied. Allow microphone access in Safari Settings, then try again.";if(code==="audio-capture")return "Safari could not access the microphone. Check microphone permission and try again.";if(code==="network")return "Speech recognition could not reach its service. Check the internet connection and try again.";if(code==="no-speech")return "No speech was heard. Tap Start Listening and try again.";return code?`Speech recognition error: ${code}. Try again.`:"None"}
function init(doc=typeof document!=="undefined"?document:null){if(!doc)return null;
 const byId=id=>doc.getElementById(id),select=byId("questionSelect"),Recognition=window.SpeechRecognition||window.webkitSpeechRecognition,clock=createAttemptClock();let recognition=null,attempt=null,listening=false,events=[];
 const now=()=>performance.now(),log=(event,details={})=>{const at=now(),row={at:Math.round(at*10)/10,event,...details};events.push(row);const li=doc.createElement("li");li.innerHTML=`<time>${at.toFixed(1)}</time><b>${event}</b><code></code>`;li.querySelector("code").textContent=JSON.stringify(details);byId("eventLog").prepend(li)};
 const setListening=value=>{listening=value;byId("status").textContent=value?"Listening — answer whenever ready":"Not listening";byId("listeningStatus").textContent=value?"READY — speak now":"Not listening";byId("statusDot").classList.toggle("live",value);byId("listenButton").classList.toggle("listening",value);byId("listenButton").textContent=value?"Stop listening":"Start listening"};
 function accept(result){const acceptedAt=now();if(!clock.recordAccepted(acceptedAt))return;byId("correct").hidden=false;byId("matchDecision").textContent="ACCEPTED";byId("matchReason").textContent=result.reason;renderMetrics();log("accepted",{attemptId:clock.current().attemptId,score:result.score,matchedAnswer:result.matchedAnswer,reason:result.reason,speechToCorrectMs:clock.metrics().speechToCorrectMs})}
 const beginAttempt=()=>{clock.reset();attempt=createAttempt(accept);byId("interim").textContent="—";byId("finalTranscript").textContent="—";byId("matchDecision").textContent="Waiting for speech";byId("matchReason").textContent="The matcher will explain every decision.";byId("correct").hidden=true;["firstLatency","correctLatency","matchLatency"].forEach(id=>byId(id).textContent="Unavailable");byId("speechStartSource").textContent="Unavailable";log("attempt reset",clock.current())};
 const renderQuestion=()=>{const q=QUESTIONS[select.selectedIndex];byId("question").textContent=q.question;byId("canonical").textContent=q.canonical;byId("approved").textContent=q.approved.join(" · ");beginAttempt()};
 function renderMetrics(){const metrics=clock.metrics();byId("firstLatency").textContent=formatLatency(metrics.speechToFirstMs);byId("correctLatency").textContent=formatLatency(metrics.speechToCorrectMs);byId("matchLatency").textContent=formatLatency(metrics.firstToCorrectMs)}
 const recordActivity=source=>{const at=now(),recorded=clock.recordSpeechActivity(source,at);if(recorded){byId("speechStartSource").textContent=source;renderMetrics()}log(source,{attemptId:clock.current().attemptId,recorded})};
 const handleResult=event=>{const q=QUESTIONS[select.selectedIndex];let interim="",finalText="";if(!attempt)beginAttempt();for(let i=event.resultIndex;i<event.results.length;i++){const result=event.results[i],text=result[0].transcript.trim(),isFinal=result.isFinal,confidence=Number.isFinite(result[0].confidence)?result[0].confidence:null,at=now();if(!clock.recordTranscript(isFinal,at))continue;if(isFinal)finalText+=text;else interim+=text;if(clock.current().firstSpeechActivityAt==null)byId("speechStartSource").textContent="first transcript fallback (latency unavailable)";renderMetrics();const match=attempt.process(text,{question:q,isFinal,confidence});log(isFinal?"final transcript":"interim transcript",{attemptId:clock.current().attemptId,transcript:text,confidence,score:match.score,matchedAnswer:match.matchedAnswer,reason:match.reason,decision:match.accepted?"accepted":"rejected",newAcceptance:match.newAcceptance});if(!attempt.isAccepted()){byId("matchDecision").textContent=match.accepted?"ACCEPTED":"NOT YET ACCEPTED";byId("matchReason").textContent=match.reason}}
  if(interim)byId("interim").textContent=interim;if(finalText)byId("finalTranscript").textContent=finalText};
 function showError(error){const message=friendlyRecognitionError(error);byId("recognitionError").textContent=message;byId("listeningStatus").textContent="Could not start";byId("supportNote").textContent=message}
 function start(){if(!window.isSecureContext){showError("insecure-context");log("recognition error",{error:"insecure-context"});return}if(!Recognition){showError("unsupported");log("recognition error",{error:"unsupported"});return}try{recognition?.abort()}catch{}beginAttempt();recognition=new Recognition();recognition.continuous=true;recognition.interimResults=true;recognition.lang="en-US";recognition.onspeechstart=()=>recordActivity("browser speechstart");recognition.onsoundstart=()=>recordActivity("current audio activity");recognition.onaudiostart=()=>log("audio start",{attemptId:clock.current().attemptId});recognition.onresult=handleResult;recognition.onerror=event=>{setListening(false);showError(event.error);log("recognition error",{attemptId:clock.current().attemptId,error:event.error,message:event.message||""})};recognition.onend=()=>{setListening(false);log("recognition ended",{attemptId:clock.current().attemptId})};try{recognition.start();byId("recognitionError").textContent="None";setListening(true);log("recognition started",{attemptId:clock.current().attemptId,interimResults:true,continuous:true})}catch(error){showError(error?.name||"start-failed");log("recognition error",{attemptId:clock.current().attemptId,error:error?.name||"start-failed"})}}
 select.innerHTML=QUESTIONS.map((q,i)=>`<option value="${i}">${i+1}. ${q.question}</option>`).join("");select.addEventListener("change",renderQuestion);byId("listenButton").addEventListener("click",()=>listening?(recognition?.stop(),setListening(false)):start());byId("resetButton").addEventListener("click",beginAttempt);byId("copyLog").addEventListener("click",()=>navigator.clipboard?.writeText(JSON.stringify(events,null,2)));byId("secureStatus").textContent=window.isSecureContext?"YES":"NO — open the HTTPS link";byId("recognitionStatus").textContent=Recognition?"SUPPORTED":"NOT SUPPORTED ON THIS BROWSER";byId("supportNote").textContent=Recognition?"Browser speech recognition detected. Tap Start Listening, then allow microphone access if asked.":"This Safari version does not provide browser speech recognition. No microphone test can run here.";renderQuestion();return {beginAttempt,getEvents:()=>events.slice(),getAttempt:clock.current}}
 return {QUESTIONS,normalize,meaningful,editDistance,evaluate,createAttempt,createAttemptClock,formatLatency,friendlyRecognitionError,init};
});
if(typeof document!=="undefined")document.addEventListener("DOMContentLoaded",()=>window.VoiceLab.init());
